/** Noms d’onglets standardisés (par saison) TEST */
var SHEETS = {
  INSCRIPTIONS: 'INSCRIPTIONS',
  ARTICLES: 'ARTICLES',
  ANNULATIONS_INSCRIPTIONS: 'ANNULATIONS_INSCRIPTIONS',
  ANNULATIONS_ARTICLES: 'ANNULATIONS_ARTICLES',
  REGLES_ARTICLES: 'REGLES_ARTICLES',
  MAPPINGS: 'MAPPINGS',
  CAPACITES: 'CAPACITES',
  PARAMS: 'PARAMS',
  IMPORT_LOG: 'IMPORT_LOG',
  MAIL_OUTBOX: 'MAIL_OUTBOX',
  MAIL_LOG: 'MAIL_LOG',
  ERREURS: 'ERREURS',
  STAGING_INSCRIPTIONS: 'STAGING_INSCRIPTIONS',
  STAGING_ARTICLES: 'STAGING_ARTICLES',
  EXPORT_LOG: 'EXPORT_LOG',
  MODIFS_INSCRIPTIONS: 'MODIFS_INSCRIPTIONS' // v0.7 — log champ-à-champ des modifications
};

/** Clés de paramètres (si stockés dans PARAMS ou Properties) */
var PARAM_KEYS = {
  DRIVE_FOLDER_IMPORTS: 'DRIVE_FOLDER_IMPORTS',
  FILE_PATTERN_INSCRIPTIONS: 'FILE_PATTERN_INSCRIPTIONS',
  FILE_PATTERN_ARTICLES: 'FILE_PATTERN_ARTICLES',

  DRY_RUN: 'DRY_RUN',
  MOVE_CONVERTED_TO_ARCHIVE: 'MOVE_CONVERTED_TO_ARCHIVE',
  INCREMENTAL_ON: 'INCREMENTAL_ON',
  KEY_COLS: 'KEY_COLS',
  SEASON_LABEL: 'SEASON_LABEL', // utilisé par le staging

  // Annulations
  ANNULATIONS_ACTIVE: 'ANNULATIONS_ACTIVE',
  STATUS_COL_INSCRIPTIONS: 'STATUS_COL_INSCRIPTIONS',
  STATUS_COL_ARTICLES: 'STATUS_COL_ARTICLES',
  STATUS_CANCEL_VALUES: 'STATUS_CANCEL_VALUES',
  STATUS_CANCEL_DATE_COL: 'STATUS_CANCEL_DATE_COL', // ex. "Date d'annulation"

  // Emails (worker & templates)
  MAIL_FROM: 'MAIL_FROM',
  MAIL_BATCH_MAX: 'MAIL_BATCH_MAX',

  MAIL_TEMPLATE_INSCRIPTION_NEW_SUBJECT: 'MAIL_TEMPLATE_INSCRIPTION_NEW_SUBJECT',
  MAIL_TEMPLATE_INSCRIPTION_NEW_BODY:    'MAIL_TEMPLATE_INSCRIPTION_NEW_BODY',

  // Récupération des emails sur la ligne inscription
  TO_FIELDS_INSCRIPTIONS: 'TO_FIELDS_INSCRIPTIONS', // CSV des colonnes à concaténer (défaut: Courriel,Parent 1 - Courriel,Parent 2 - Courriel)

  // Résumés par secteur (U4-U8, U9-U12, U13-U18)
  MAIL_TO_SUMMARY_U4U8:   'MAIL_TO_SUMMARY_U4U8',
  MAIL_CC_SUMMARY_U4U8:   'MAIL_CC_SUMMARY_U4U8',
  MAIL_TO_SUMMARY_U9U12:  'MAIL_TO_SUMMARY_U9U12',
  MAIL_CC_SUMMARY_U9U12:  'MAIL_CC_SUMMARY_U9U12',
  MAIL_TO_SUMMARY_U13U18: 'MAIL_TO_SUMMARY_U13U18',
  MAIL_CC_SUMMARY_U13U18: 'MAIL_CC_SUMMARY_U13U18',
  MAIL_TEMPLATE_SUMMARY_SUBJECT: 'MAIL_TEMPLATE_SUMMARY_SUBJECT',
  MAIL_TEMPLATE_SUMMARY_BODY:    'MAIL_TEMPLATE_SUMMARY_BODY',

  // Règles
  RULES_ON: 'RULES_ON',
  RULES_SEVERITY_THRESHOLD: 'RULES_SEVERITY_THRESHOLD', // 'warn'|'error'
  RULES_APPEND: 'RULES_APPEND',
  RULES_DRY_RUN: 'RULES_DRY_RUN',
  RULES_MAX_ROWS: 'RULES_MAX_ROWS',

  // Export modifs
  EXPORT_MODIFIED_SINCE_DAYS: 'EXPORT_MODIFIED_SINCE_DAYS'
};

/** Colonnes de contrôle (ajoutées côté FINALS) */
var CONTROL_COLS = {
  ROW_HASH: 'ROW_HASH',
  CANCELLED: 'CANCELLED',
  EXCLUDE_FROM_EXPORT: 'EXCLUDE_FROM_EXPORT',
  LAST_MODIFIED_AT: 'LAST_MODIFIED_AT' // v0.7 — ISO datetime quand on détecte une modification
};

var ARCHIVE = {
  ROOT_SUBFOLDER: 'Archives',
  DATE_FMT: 'yyyy-MM-dd'
};

/** En-tête canonique pour MAIL_OUTBOX */
function getMailOutboxHeaders_() {
  return ['Type','To','Cc','Sujet','Corps','Attachments','KeyHash','Status','CreatedAt','SentAt','Error'];
}
